IF
Global("O#LLQuestPalace","GLOBAL",2)
OR(6)
Range(Player1,15)
Range(Player2,15)
Range(Player3,15)
Range(Player4,15)
Range(Player5,15)
Range(Player6,15)
InMyArea(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID) 
!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END

IF
AttackedBy([GOODCUTOFF],DEFAULT)
Global("O#LLReturnHomeArte","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("O#LLReturnHomeArte","GLOBAL",1)
DestroySelf()
END